language: go

branches:
  only:
      - master
      - develop

go:
  - 1.5
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.6
  - 1.6.1
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.7
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - 1.7.4

install:
  - go get -v github.com/Masterminds/glide
  - glide update
  - make build

notifications:
  email: false
  slack: iverware:cxnyQSypmixurFcLYYciYyq7
